#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: d2bl-production
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-19831447-1"

staging:
  stack: cedar
  app: d2bl-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
  addons:
    - pgbackups:auto-week
    - memcache:5mb
    - logging:basic
    - scheduler:standard
